<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DeadMoney.Core\DeadMoney.Core.csproj" />
		<ProjectReference Include="..\DeadMoney.Data\DeadMoney.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>