// <auto-generated />
using System;
using DeadMoney.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeadMoney.Data.Migrations
{
    [DbContext(typeof(DeadMoneyDbContext))]
    [Migration("20260212024646_ContractImportAdjustments")]
    partial class ContractImportAdjustments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModifiedBySim")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SigningBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGuaranteed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Contracts", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapNumber")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVoidYear")
                        .HasColumnType("bit");

                    b.Property<decimal>("OptionBonusProration")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerGameRosterBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RosterBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SigningBonusProration")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("WorkoutBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TeamId");

                    b.ToTable("ContractYears", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.LeagueSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalaryCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeagueSettings", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("College")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("int");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("int");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GsisId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeadshotUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtcId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PfrId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("YearsExp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Positions", "League");

                    b.HasData(
                        new
                        {
                            Code = "QB",
                            DisplayOrder = 1,
                            Name = "Quarterback",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "RB",
                            DisplayOrder = 2,
                            Name = "Running Back",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "FB",
                            DisplayOrder = 3,
                            Name = "Fullback",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "WR",
                            DisplayOrder = 4,
                            Name = "Wide Receiver",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "TE",
                            DisplayOrder = 5,
                            Name = "Tight End",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "OT",
                            DisplayOrder = 6,
                            Name = "Offensive Tackle",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "G",
                            DisplayOrder = 7,
                            Name = "Offensive Guard",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "C",
                            DisplayOrder = 8,
                            Name = "Center",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "EDGE",
                            DisplayOrder = 10,
                            Name = "Edge Defender",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "DT",
                            DisplayOrder = 11,
                            Name = "Interior Defensive Line",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "LB",
                            DisplayOrder = 12,
                            Name = "Linebacker",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "CB",
                            DisplayOrder = 13,
                            Name = "Cornerback",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "S",
                            DisplayOrder = 14,
                            Name = "Safety",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "K",
                            DisplayOrder = 20,
                            Name = "Kicker",
                            Unit = "SpecialTeams"
                        },
                        new
                        {
                            Code = "P",
                            DisplayOrder = 21,
                            Name = "Punter",
                            Unit = "SpecialTeams"
                        },
                        new
                        {
                            Code = "LS",
                            DisplayOrder = 22,
                            Name = "Long Snapper",
                            Unit = "SpecialTeams"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Commissioner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Agent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "GM"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Assistant GM"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CarryoverCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Teams", "League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ARI",
                            CarryoverCap = 0m,
                            City = "Arizona",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Cardinals"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "ATL",
                            CarryoverCap = 0m,
                            City = "Atlanta",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Falcons"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "BAL",
                            CarryoverCap = 0m,
                            City = "Baltimore",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Ravens"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "BUF",
                            CarryoverCap = 0m,
                            City = "Buffalo",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CAR",
                            CarryoverCap = 0m,
                            City = "Carolina",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Panthers"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "CHI",
                            CarryoverCap = 0m,
                            City = "Chicago",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Bears"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "CIN",
                            CarryoverCap = 0m,
                            City = "Cincinnati",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Bengals"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "CLE",
                            CarryoverCap = 0m,
                            City = "Cleveland",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Browns"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "DAL",
                            CarryoverCap = 0m,
                            City = "Dallas",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Cowboys"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "DEN",
                            CarryoverCap = 0m,
                            City = "Denver",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Broncos"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "DET",
                            CarryoverCap = 0m,
                            City = "Detroit",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Lions"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "GB",
                            CarryoverCap = 0m,
                            City = "Green Bay",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Packers"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "HOU",
                            CarryoverCap = 0m,
                            City = "Houston",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Texans"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "IND",
                            CarryoverCap = 0m,
                            City = "Indianapolis",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Colts"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "JAX",
                            CarryoverCap = 0m,
                            City = "Jacksonville",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Jaguars"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "KC",
                            CarryoverCap = 0m,
                            City = "Kansas City",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Chiefs"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "LV",
                            CarryoverCap = 0m,
                            City = "Las Vegas",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Raiders"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "LAC",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Chargers"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "LAR",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Rams"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "MIA",
                            CarryoverCap = 0m,
                            City = "Miami",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Dolphins"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "MIN",
                            CarryoverCap = 0m,
                            City = "Minnesota",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Vikings"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "NE",
                            CarryoverCap = 0m,
                            City = "New England",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Patriots"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "NO",
                            CarryoverCap = 0m,
                            City = "New Orleans",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Saints"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "NYG",
                            CarryoverCap = 0m,
                            City = "New York",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Giants"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "NYJ",
                            CarryoverCap = 0m,
                            City = "New York",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Jets"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "PHI",
                            CarryoverCap = 0m,
                            City = "Philadelphia",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Eagles"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "PIT",
                            CarryoverCap = 0m,
                            City = "Pittsburgh",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Steelers"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "SF",
                            CarryoverCap = 0m,
                            City = "San Francisco",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "49ers"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "SEA",
                            CarryoverCap = 0m,
                            City = "Seattle",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Seahawks"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "TB",
                            CarryoverCap = 0m,
                            City = "Tampa Bay",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Buccaneers"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "TEN",
                            CarryoverCap = 0m,
                            City = "Tennessee",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Titans"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "WAS",
                            CarryoverCap = 0m,
                            City = "Washington",
                            Conference = "",
                            Division = "",
                            Name = "",
                            Nickname = "Commanders"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseTeamColorsAsAccent")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "Auth");
                });

            modelBuilder.Entity("PositionUserRole", b =>
                {
                    b.Property<string>("PositionsCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserRolesId")
                        .HasColumnType("int");

                    b.HasKey("PositionsCode", "UserRolesId");

                    b.HasIndex("UserRolesId");

                    b.ToTable("UserRolePositions", "Auth");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Contract", "Contract")
                        .WithMany("ContractYears")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Contract");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId");

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.UserRole", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany("UserRoles")
                        .HasForeignKey("TeamId");

                    b.HasOne("DeadMoney.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositionUserRole", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionsCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Navigation("ContractYears");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Navigation("Roster");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
