// <auto-generated />
using System;
using DeadMoney.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeadMoney.Data.Migrations
{
    [DbContext(typeof(DeadMoneyDbContext))]
    [Migration("20260210190017_Branding")]
    partial class Branding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeadMoney.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "Auth");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SigningBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Contracts", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonuses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProratedSigningBonus")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractYears", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.LeagueSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalaryCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeagueSettings", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SleeperId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Positions", "League");

                    b.HasData(
                        new
                        {
                            Code = "QB",
                            DisplayOrder = 1,
                            Name = "Quarterback",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "RB",
                            DisplayOrder = 2,
                            Name = "Running Back",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "FB",
                            DisplayOrder = 3,
                            Name = "Fullback",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "WR",
                            DisplayOrder = 4,
                            Name = "Wide Receiver",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "TE",
                            DisplayOrder = 5,
                            Name = "Tight End",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "OT",
                            DisplayOrder = 6,
                            Name = "Offensive Tackle",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "G",
                            DisplayOrder = 7,
                            Name = "Offensive Guard",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "C",
                            DisplayOrder = 8,
                            Name = "Center",
                            Unit = "Offense"
                        },
                        new
                        {
                            Code = "EDGE",
                            DisplayOrder = 10,
                            Name = "Edge Defender",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "DT",
                            DisplayOrder = 11,
                            Name = "Interior Defensive Line",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "LB",
                            DisplayOrder = 12,
                            Name = "Linebacker",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "CB",
                            DisplayOrder = 13,
                            Name = "Cornerback",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "S",
                            DisplayOrder = 14,
                            Name = "Safety",
                            Unit = "Defense"
                        },
                        new
                        {
                            Code = "K",
                            DisplayOrder = 20,
                            Name = "Kicker",
                            Unit = "SpecialTeams"
                        },
                        new
                        {
                            Code = "P",
                            DisplayOrder = 21,
                            Name = "Punter",
                            Unit = "SpecialTeams"
                        },
                        new
                        {
                            Code = "LS",
                            DisplayOrder = 22,
                            Name = "Long Snapper",
                            Unit = "SpecialTeams"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CarryoverCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Teams", "League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ARI",
                            CarryoverCap = 0m,
                            City = "Arizona",
                            Name = "",
                            Nickname = "Cardinals"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "ATL",
                            CarryoverCap = 0m,
                            City = "Atlanta",
                            Name = "",
                            Nickname = "Falcons"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "BAL",
                            CarryoverCap = 0m,
                            City = "Baltimore",
                            Name = "",
                            Nickname = "Ravens"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "BUF",
                            CarryoverCap = 0m,
                            City = "Buffalo",
                            Name = "",
                            Nickname = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CAR",
                            CarryoverCap = 0m,
                            City = "Carolina",
                            Name = "",
                            Nickname = "Panthers"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "CHI",
                            CarryoverCap = 0m,
                            City = "Chicago",
                            Name = "",
                            Nickname = "Bears"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "CIN",
                            CarryoverCap = 0m,
                            City = "Cincinnati",
                            Name = "",
                            Nickname = "Bengals"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "CLE",
                            CarryoverCap = 0m,
                            City = "Cleveland",
                            Name = "",
                            Nickname = "Browns"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "DAL",
                            CarryoverCap = 0m,
                            City = "Dallas",
                            Name = "",
                            Nickname = "Cowboys"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "DEN",
                            CarryoverCap = 0m,
                            City = "Denver",
                            Name = "",
                            Nickname = "Broncos"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "DET",
                            CarryoverCap = 0m,
                            City = "Detroit",
                            Name = "",
                            Nickname = "Lions"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "GB",
                            CarryoverCap = 0m,
                            City = "Green Bay",
                            Name = "",
                            Nickname = "Packers"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "HOU",
                            CarryoverCap = 0m,
                            City = "Houston",
                            Name = "",
                            Nickname = "Texans"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "IND",
                            CarryoverCap = 0m,
                            City = "Indianapolis",
                            Name = "",
                            Nickname = "Colts"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "JAX",
                            CarryoverCap = 0m,
                            City = "Jacksonville",
                            Name = "",
                            Nickname = "Jaguars"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "KC",
                            CarryoverCap = 0m,
                            City = "Kansas City",
                            Name = "",
                            Nickname = "Chiefs"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "LV",
                            CarryoverCap = 0m,
                            City = "Las Vegas",
                            Name = "",
                            Nickname = "Raiders"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "LAC",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Name = "",
                            Nickname = "Chargers"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "LAR",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Name = "",
                            Nickname = "Rams"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "MIA",
                            CarryoverCap = 0m,
                            City = "Miami",
                            Name = "",
                            Nickname = "Dolphins"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "MIN",
                            CarryoverCap = 0m,
                            City = "Minnesota",
                            Name = "",
                            Nickname = "Vikings"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "NE",
                            CarryoverCap = 0m,
                            City = "New England",
                            Name = "",
                            Nickname = "Patriots"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "NO",
                            CarryoverCap = 0m,
                            City = "New Orleans",
                            Name = "",
                            Nickname = "Saints"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "NYG",
                            CarryoverCap = 0m,
                            City = "New York",
                            Name = "",
                            Nickname = "Giants"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "NYJ",
                            CarryoverCap = 0m,
                            City = "New York",
                            Name = "",
                            Nickname = "Jets"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "PHI",
                            CarryoverCap = 0m,
                            City = "Philadelphia",
                            Name = "",
                            Nickname = "Eagles"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "PIT",
                            CarryoverCap = 0m,
                            City = "Pittsburgh",
                            Name = "",
                            Nickname = "Steelers"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "SF",
                            CarryoverCap = 0m,
                            City = "San Francisco",
                            Name = "",
                            Nickname = "49ers"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "SEA",
                            CarryoverCap = 0m,
                            City = "Seattle",
                            Name = "",
                            Nickname = "Seahawks"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "TB",
                            CarryoverCap = 0m,
                            City = "Tampa Bay",
                            Name = "",
                            Nickname = "Buccaneers"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "TEN",
                            CarryoverCap = 0m,
                            City = "Tennessee",
                            Name = "",
                            Nickname = "Titans"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "WAS",
                            CarryoverCap = 0m,
                            City = "Washington",
                            Name = "",
                            Nickname = "Commanders"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Auth");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Player", null)
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Contract", null)
                        .WithMany("Years")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId");

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Navigation("Years");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
