// <auto-generated />
using System;
using DeadMoney.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeadMoney.Data.Migrations
{
    [DbContext(typeof(DeadMoneyDbContext))]
    partial class DeadMoneyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModifiedBySim")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("SigningBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGuaranteed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Contracts", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsVoidYear")
                        .HasColumnType("bit");

                    b.Property<decimal>("OptionBonusProration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerGameRosterBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RosterBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SigningBonusProration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("WorkoutBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "Year")
                        .HasDatabaseName("IX_ContractYears_TeamId_Year");

                    b.ToTable("ContractYears", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.DraftPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("PickNumber")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("OriginalTeamId");

                    b.ToTable("DraftPicks", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.FaOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualValueM")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GuaranteedM")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValueM")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Years")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "PlayerId");

                    b.ToTable("FaOffers", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.LeagueSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<decimal>("SalaryCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeagueSettings", "League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCurrent = false,
                            SalaryCap = 279200000m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            IsCurrent = true,
                            SalaryCap = 279200000m,
                            Year = 2027
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("College")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DraftPick")
                        .HasColumnType("int");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("int");

                    b.Property<int?>("DraftYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GsisId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeadshotUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtcId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PfrId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("YearsExp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsRetired");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Positions", "League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "QB",
                            DisplayOrder = 1,
                            Name = "Quarterback",
                            Unit = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "RB",
                            DisplayOrder = 2,
                            Name = "Running Back",
                            Unit = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "FB",
                            DisplayOrder = 3,
                            Name = "Fullback",
                            Unit = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "WR",
                            DisplayOrder = 4,
                            Name = "Wide Receiver",
                            Unit = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "TE",
                            DisplayOrder = 5,
                            Name = "Tight End",
                            Unit = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "OT",
                            DisplayOrder = 6,
                            Name = "Offensive Tackle",
                            Unit = 0
                        },
                        new
                        {
                            Id = 7,
                            Code = "G",
                            DisplayOrder = 7,
                            Name = "Offensive Guard",
                            Unit = 0
                        },
                        new
                        {
                            Id = 8,
                            Code = "C",
                            DisplayOrder = 8,
                            Name = "Center",
                            Unit = 0
                        },
                        new
                        {
                            Id = 9,
                            Code = "EDGE",
                            DisplayOrder = 10,
                            Name = "Edge Defender",
                            Unit = 1
                        },
                        new
                        {
                            Id = 10,
                            Code = "DT",
                            DisplayOrder = 11,
                            Name = "Interior Defensive Line",
                            Unit = 1
                        },
                        new
                        {
                            Id = 11,
                            Code = "LB",
                            DisplayOrder = 12,
                            Name = "Linebacker",
                            Unit = 1
                        },
                        new
                        {
                            Id = 12,
                            Code = "CB",
                            DisplayOrder = 13,
                            Name = "Cornerback",
                            Unit = 1
                        },
                        new
                        {
                            Id = 13,
                            Code = "S",
                            DisplayOrder = 14,
                            Name = "Safety",
                            Unit = 1
                        },
                        new
                        {
                            Id = 14,
                            Code = "K",
                            DisplayOrder = 20,
                            Name = "Kicker",
                            Unit = 2
                        },
                        new
                        {
                            Id = 15,
                            Code = "P",
                            DisplayOrder = 21,
                            Name = "Punter",
                            Unit = 2
                        },
                        new
                        {
                            Id = 16,
                            Code = "LS",
                            DisplayOrder = 22,
                            Name = "Long Snapper",
                            Unit = 2
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full administrative access to league settings and users.",
                            Name = "Commissioner"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manages specific player positions across the league.",
                            Name = "Agent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Manages a specific team's roster and salary cap.",
                            Name = "GM"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Assists in managing team operations.",
                            Name = "Assistant GM"
                        },
                        new
                        {
                            Id = 5,
                            Description = "System administrator with full access to all features and settings.",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CarryoverCap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Teams", "League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ARI",
                            CarryoverCap = 0m,
                            City = "Arizona",
                            Conference = "NFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Cardinals"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "ATL",
                            CarryoverCap = 0m,
                            City = "Atlanta",
                            Conference = "NFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Falcons"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "BAL",
                            CarryoverCap = 0m,
                            City = "Baltimore",
                            Conference = "AFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Ravens"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "BUF",
                            CarryoverCap = 0m,
                            City = "Buffalo",
                            Conference = "AFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Bills"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CAR",
                            CarryoverCap = 0m,
                            City = "Carolina",
                            Conference = "NFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Panthers"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "CHI",
                            CarryoverCap = 0m,
                            City = "Chicago",
                            Conference = "NFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Bears"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "CIN",
                            CarryoverCap = 0m,
                            City = "Cincinnati",
                            Conference = "AFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Bengals"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "CLE",
                            CarryoverCap = 0m,
                            City = "Cleveland",
                            Conference = "AFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Browns"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "DAL",
                            CarryoverCap = 0m,
                            City = "Dallas",
                            Conference = "NFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Cowboys"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "DEN",
                            CarryoverCap = 0m,
                            City = "Denver",
                            Conference = "AFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Broncos"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "DET",
                            CarryoverCap = 0m,
                            City = "Detroit",
                            Conference = "NFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Lions"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "GB",
                            CarryoverCap = 0m,
                            City = "Green Bay",
                            Conference = "NFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Packers"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "HOU",
                            CarryoverCap = 0m,
                            City = "Houston",
                            Conference = "AFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Texans"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "IND",
                            CarryoverCap = 0m,
                            City = "Indianapolis",
                            Conference = "AFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Colts"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "JAX",
                            CarryoverCap = 0m,
                            City = "Jacksonville",
                            Conference = "AFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Jaguars"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "KC",
                            CarryoverCap = 0m,
                            City = "Kansas City",
                            Conference = "AFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Chiefs"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "LV",
                            CarryoverCap = 0m,
                            City = "Las Vegas",
                            Conference = "AFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Raiders"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "LAC",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Conference = "AFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Chargers"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "LAR",
                            CarryoverCap = 0m,
                            City = "Los Angeles",
                            Conference = "NFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Rams"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "MIA",
                            CarryoverCap = 0m,
                            City = "Miami",
                            Conference = "AFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Dolphins"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "MIN",
                            CarryoverCap = 0m,
                            City = "Minnesota",
                            Conference = "NFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Vikings"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "NE",
                            CarryoverCap = 0m,
                            City = "New England",
                            Conference = "AFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Patriots"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "NO",
                            CarryoverCap = 0m,
                            City = "New Orleans",
                            Conference = "NFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Saints"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "NYG",
                            CarryoverCap = 0m,
                            City = "New York",
                            Conference = "NFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Giants"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "NYJ",
                            CarryoverCap = 0m,
                            City = "New York",
                            Conference = "AFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Jets"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "PHI",
                            CarryoverCap = 0m,
                            City = "Philadelphia",
                            Conference = "NFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Eagles"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "PIT",
                            CarryoverCap = 0m,
                            City = "Pittsburgh",
                            Conference = "AFC",
                            Division = "North",
                            Name = "",
                            Nickname = "Steelers"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "SF",
                            CarryoverCap = 0m,
                            City = "San Francisco",
                            Conference = "NFC",
                            Division = "West",
                            Name = "",
                            Nickname = "49ers"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "SEA",
                            CarryoverCap = 0m,
                            City = "Seattle",
                            Conference = "NFC",
                            Division = "West",
                            Name = "",
                            Nickname = "Seahawks"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "TB",
                            CarryoverCap = 0m,
                            City = "Tampa Bay",
                            Conference = "NFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Buccaneers"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "TEN",
                            CarryoverCap = 0m,
                            City = "Tennessee",
                            Conference = "AFC",
                            Division = "South",
                            Name = "",
                            Nickname = "Titans"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "WAS",
                            CarryoverCap = 0m,
                            City = "Washington",
                            Conference = "NFC",
                            Division = "East",
                            Name = "",
                            Nickname = "Commanders"
                        });
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DraftPickId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("ToTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DraftPickId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ToTeamId");

                    b.ToTable("Transactions", "League");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseTeamColorsAsAccent")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "Auth");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.ContractYear", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Contract", "Contract")
                        .WithMany("ContractYears")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Contract");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.FaOffer", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "OriginalTeam")
                        .WithMany()
                        .HasForeignKey("OriginalTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("OriginalTeam");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Transaction", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.DraftPick", "DraftPick")
                        .WithMany()
                        .HasForeignKey("DraftPickId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeadMoney.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeadMoney.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DraftPick");

                    b.Navigation("Player");

                    b.Navigation("Team");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.UserRole", b =>
                {
                    b.HasOne("DeadMoney.Core.Entities.Position", "Position")
                        .WithMany("UserRoles")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeadMoney.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeadMoney.Core.Entities.Team", "Team")
                        .WithMany("UserRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeadMoney.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Contract", b =>
                {
                    b.Navigation("ContractYears");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Player", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.Team", b =>
                {
                    b.Navigation("Roster");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DeadMoney.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
